### ISSUE TITLE
start scene

### ISSUE THREAD

**Issue by RichardMarks** [RichardMarks/coin-collector-mobile#22]
we need some sort of start scene for the game

we need to setup the initial board state and transition seamlessly to the play scene from this scene when the user touches the screen/clicks (should show a flashing touch to start text in the center of the scene)

at a minimum we need to update and render the scene

`proc updateStartScene(scene: Scene, deltaTime: float)`
`proc renderStartScene(scene: Scene, deltaTime: float)`

**Comment by stephenc222** [comment]
We've decided to create separate play and start states within the play scene, and thus no longer need a separate start scene.
