### ISSUE TITLE
play scene start state board renderer

### ISSUE THREAD

**Issue by RichardMarks** [RichardMarks/coin-collector-mobile#24]
we need to render the board tiles in the start state of the play scene

I thought that it would be cool to animate the construction of the board by having each tile on the board fall down at random from off the top of the screen into it's final board position.

care must be taken such that the rendering depth is not out of order so that tiles overlap correctly

**Comment by stephenc222** [comment]
See [3019a0e](https://github.com/RichardMarks/coin-collector-mobile/commit/3019a0e25b44783964a471fe64e63bf945230b27) for initial implementation of start state "blinking" text for kicking off the game
