### ISSUE TITLE
slightly add skill to game play

### ISSUE THREAD

**Issue by stephenc222** [RichardMarks/coin-collector-mobile#46]
All gameplay is controlled by random chance, and the game would be a little more fun if there was a chance for player skill to play a part.

First idea from Richard:

- every 5-15 seconds, make the tiles that have pits wiggle slightly, and for less than say half or a quarter second, so players that are better at remembering which tiles wiggled, will score higher.

**Comment by RichardMarks** [comment]
another idea:
+ in the `starting` play mode, all board tiles are revealed for a moment before the board stones are dropped on top to cover them. This effectively turns the game into a memorization challenge

**Comment by stephenc222** [comment]
I like that idea @RichardMarks for revealing all board tiles for a moment at the beginning of game play.
